name: "Run Python Tests"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  pull_request_target:
    branches:
      - master

jobs:
  lint-markdown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Lint changelog file
        uses: nosborn/github-action-markdown-cli@v3.0.1
        with:
          files: .
          config_file: .markdownlint.yaml

      - name: Push Linted Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Fix Markdown Styling
