name: "Run Python Tests"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  pull_request_target:
    branches:
      - master

jobs:
  lint-markdown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Lint changelog file
        uses: avtodev/markdown-lint@v1
        with:
          config: '.markdownlint.json'
          args: '.'
        env:
          INPUT_FIX: true
